sudo: required

services:
  - docker

before_install:
  - docker build -t williamabboud6669/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true williamabboud6669/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-038507185201"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main